apiVersion: v1
kind: Service
metadata:
  labels:
    app: syslog-ng
  name: syslog-ng
  namespace: default
spec:
  ports:
  - port: 5514
    protocol: UDP
    targetPort: 5514
    name: udp
  - port: 6601
    protocol: TCP
    targetPort: 6601
    name: tcp
  - port: 9080
    protocol: TCP
    name: promtail
  selector:
    app: syslog-ng
  sessionAffinity: None
  type: NodePort
