apiVersion: v1
data:
  config.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: syslog-ng
          __path__: /logs/hosts/*
      pipeline_stages:
      - match:
          selector: '{job="syslog-ng"}'
          stages:
            - regex:
                    expression: "^\\w{3} \\d+ \\d{2}:\\d{2}:\\d{2} (?P<TRANSPORT>\\d+\\.\\d+\\.\\d+\\.\\d+) (?P<SYSLOG_IDENTIFIER>(\\w+|\\w+-\\w+))(\\:|\\[\\d+\\]:)"
            - labels:
                TRANSPORT:
                SYSLOG_IDENTIFIER:

kind: ConfigMap
metadata:
  name: syslog-ng-configmap
  namespace: default
